ci/ci-tron: add check that the required variables are set
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/34795>

diff --git a/.gitlab-ci/test/gitlab-ci.yml b/.gitlab-ci/test/gitlab-ci.yml
--- a/.gitlab-ci/test/gitlab-ci.yml
+++ b/.gitlab-ci/test/gitlab-ci.yml
@@ -424,6 +424,14 @@ yaml-toml-shell-py-test:
 
       eval "$S3_JWT_FILE_SCRIPT"
 
+      for var in CI_TRON_DUT_SETUP_TAGS; do
+        if [[ -z "$(eval echo \${$var:-})" ]]; then
+          echo "The required variable '$var' is missing"
+          exit 1
+        fi
+      done
+
+
       # Open a section that will be closed by b2c
       echo -e "\n\e[0Ksection_start:`date +%s`:b2c_kernel_boot[collapsed=true]\r\e[0K\e[0;36m[$(cut -d ' ' -f1 /proc/uptime)]: Submitting the CI-tron job and booting the DUT\e[0m\n"
 
